export const projects = [
    {
        title: "UMTAS FIKES BEM Information System",
        category: "Full Stack Development",
        year: "2025",
        color: "from-blue-500",
        image: "/Sistem Informasi BEM FIKES UMTAS.png",
        link: "https://bemfikes.umtas.ac.id/",
    },
    {
        title: "CJA RENTCAR Management System",
        category: "Web Application",
        year: "2026",
        color: "from-purple-500",
        image: "/Sistem Informasi Manajement CJA RENTCAR.png",
        link: "#",
    },
    {
        title: "CV. Kerabat Wisata Finance System",
        category: "Web Solution",
        year: "2025",
        color: "from-emerald-500",
        image: "/Sistem Informasi Kas Masuk dan Keluar Rental CV.Kerabat Wisata.png",
        link: "#",
    },
    {
        title: "NAWADIKTI Information System",
        category: "Web Application",
        year: "2024",
        color: "from-cyan-500",
        image: "/Sistem Infomasi NAWADIKTI.png",
        link: "#",
    },
    {
        title: "PBM Pangandaran Food Stall",
        category: "Web Solution",
        year: "2026",
        color: "from-orange-500",
        image: null,
        link: "https://warungpbmpangadaran.page.gd/",
    },
    {
        title: "Restaurant Marketing Website",
        category: "Web Development (PKL)",
        year: "2020",
        color: "from-green-500",
        image: null,
        link: "#",
    },
];
